# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim
WORKDIR /app
# Install dependencies
COPY pyproject.toml uv.lock ./
COPY src ./src
RUN pip install --no-cache-dir .

ENTRYPOINT ["ida-pro-mcp", "--transport", "stdio"]
